@url = http://localhost:5004
@accessToken = xxx.xxx.xxx

###
POST {{url}}/sign-up
Content-Type: application/json

{
  "email": "pacco-user1@mailinator.com",
  "password": "secret"
}

###
POST {{url}}/sign-in
Content-Type: application/json

{
  "email": "pacco-user1@mailinator.com",
  "password": "secret"
}

###
GET {{url}}/me
Authorization: Bearer {{accessToken}}

