@url = http://localhost:5005
@accessToken = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJiNTI2OGQ3NTcxYWM0OTA3OThkM2Q2ZjY5NzgyNmM2OSIsInVuaXF1ZV9uYW1lIjoiYjUyNjhkNzU3MWFjNDkwNzk4ZDNkNmY2OTc4MjZjNjkiLCJqdGkiOiI5YTg1NjVkYS04NzNmLTQ2NTktOTY1NC1hMWJiMzJhZGUzN2YiLCJpYXQiOiIxNTYxNzUwNDM3Nzg1IiwiaHR0cDovL3NjaGVtYXMubWljcm9zb2Z0LmNvbS93cy8yMDA4LzA2L2lkZW50aXR5L2NsYWltcy9yb2xlIjoidXNlciIsIm5iZiI6MTU2MTc1MDQzNywiZXhwIjoxNTYxNzU0MDM3LCJpc3MiOiJwYWNjbyJ9.e_I5wbeWnvTmSzu137FTCBjAbrM2d2IpNjpo4Ny0K2Y

###
POST {{url}}/sign-up

{
  "email": "pacco-user1@mailinator.com",
  "password": "secret"
}

###
POST {{url}}/sign-in

{
  "email": "pacco-user1@mailinator.com",
  "password": "secret"
}

###
GET {{url}}/me
Authorization: Bearer {{accessToken}}

